# Example `config.toml` file populated with application defaults.

# Set of update types to be excluded from the updates count shown on the taskbar.
# These UpdateTypes are still checked and can be seen by opening the popup.
#
# See https://github.com/nick42d/cosmic-applet-arch/issues/28
# 
# Possible values: "aur", "devel", "pacman".
exclude_from_counter = []

# How often applet checks the local offline package database for updates.
interval_secs = 6

# Every `online_check_period` checks, the package database will be refreshed online.
# ie. The applet will check for updates online every
# `interval_secs` * `online_check_period` seconds.
online_check_period = 600
 
# Any updates check taking longer than `timeout_secs` will be cancelled and error.
timeout_secs = 120

# NOT YET IMPLEMENTED
# If you are using unofficial repositories, a package url can be provided.
# {pkgname} will be replaced with the package name.
# 
# By default this is not set, but here are some examples:
# 
# other_repo_urls.endeavouros = "https://github.com/endeavouros-team/PKGBUILDS/tree/master/{pkgname}"
# other_repo_urls.chaotic-aur = "https://gitlab.com/chaotic-aur/pkgbuilds/-/tree/main/{pkgname}"
