name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    steps:
      # Generating a GitHub token, so that PRs and tags created by
      # the release-plz-action can trigger actions workflows.
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          # GitHub App ID secret name
          app-id: ${{ secrets.APP_ID }}
          # GitHub App private key secret name
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        id: release-plz
        uses: MarcoIeni/release-plz-action@v0.5.130
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Check if cosmic-applet-arch was released
        id: check_applet_release
        if: ${{ steps.release-plz.outputs.releases_created == 'true' }}
        env:
          RELEASES: ${{ steps.release-plz.outputs.releases }}
        run: |
          APPLET_IS_RELEASED=$(jq -r 'any(.[]; .package_name == "cosmic-applet-arch")' <<< "$RELEASES")
          echo "Checking if applet was released: $APPLET_IS_RELEASED"
          echo "applet_released=$APPLET_IS_RELEASED" >> "$GITHUB_OUTPUT"
        
          if [ "$APPLET_IS_RELEASED" == "true" ]; then
             APPLET_VERSION=$(jq -r '.[] | select(.package_name == "cosmic-applet-arch") | .version' <<< "$RELEASES")
             echo "released version: $APPLET_VERSION"
             echo "applet_version=$APPLET_VERSION" >> "$GITHUB_OUTPUT"
          fi
      - name: Generate PKGBUILD
        if: ${{ steps.check_applet_release.outputs.applet_released == 'true' }}
        env:
          NEW_APPLET_VERSION: ${{ steps.check_applet_release.outputs.applet_version }}
        run: ./aur/generate_pkgbuild.sh $NEW_APPLET_VERSION
      - name: Publish AUR package
        if: ${{ steps.check_applet_release.outputs.applet_released == 'true' }}
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: cosmic-applet-arch
          pkgbuild: ./PKGBUILD
          updpkgsums: true
          test: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Auto-updated via CD
          ssh_keyscan_types: rsa,ecdsa,ed25519

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      # Generating a GitHub token, so that PRs and tags created by
      # the release-plz-action can trigger actions workflows.
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          # GitHub App ID secret name
          app-id: ${{ secrets.APP_ID }}
          # GitHub App private key secret name
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5.130
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
